# Generated by Django 4.1.7 on 2023-04-01 15:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=200, upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_photo', models.ImageField(max_length=200, upload_to='', verbose_name='Картинка с объявлением')),
                ('discount_on_photo', models.SmallIntegerField(verbose_name='Скидка на картинке')),
                ('photo', models.ImageField(max_length=200, upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(verbose_name='Размер'), size=None, verbose_name='Размеры')),
                ('old_price', models.IntegerField(verbose_name='Старая цена')),
                ('new_price', models.IntegerField(verbose_name='Новая цена')),
            ],
        ),
        migrations.CreateModel(
            name='NoveltyIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=200, upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PopularIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=200, upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Популярное',
                'verbose_name_plural': 'Популярные',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GreetingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=300, upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categorygreeting')),
            ],
            options={
                'verbose_name': 'Приветствие',
                'verbose_name_plural': 'Приветствия',
                'ordering': ['id'],
            },
        ),
    ]
